# Generated by Django 3.0.8 on 2020-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=20, unique=True)),
                ('name_ja', models.CharField(max_length=20, unique=True)),
                ('description_en', models.CharField(max_length=200)),
            ],
        ),
    ]
