# Generated by Django 3.0.8 on 2020-07-25 12:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
        migrations.AddField(
            model_name='pigment',
            name='hex_color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
