# Generated by Django 3.0.8 on 2020-07-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('description_en', models.CharField(max_length=200)),
                ('hex_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=6)),
                ('price', models.IntegerField(default=0)),
                ('pigment_type', models.CharField(choices=[('TI', 'Tennen Iwaenogu 天然岩絵具'), ('SI', 'Shin Iwaenogu\u3000新岩絵具'), ('GO', 'Gofun 胡粉'), ('SH', 'Suihi Enogu\u3000水飛絵具'), ('TT', 'Tennen Tsuchi Enogu\u3000天然土絵具')], max_length=2)),
                ('grain', models.CharField(choices=[('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('13', 'Thirteen'), ('白', 'Byaku')], default='12', max_length=2)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pigments.Color')),
            ],
        ),
        migrations.DeleteModel(
            name='Grain',
        ),
        migrations.DeleteModel(
            name='Iwaenogu',
        ),
    ]
