# Generated by Django 3.0.8 on 2020-07-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigmenttype',
            name='value',
        ),
        migrations.AddField(
            model_name='pigmenttype',
            name='description_en',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pigmenttype',
            name='name_en',
            field=models.CharField(default='Tennen Iwaenogu', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pigmenttype',
            name='name_ja',
            field=models.CharField(default='天然岩絵具', max_length=50),
            preserve_default=False,
        ),
    ]
