# Generated by Django 4.0.6 on 2022-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
