# Generated by Django 3.0.8 on 2020-07-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('description_en', models.CharField(max_length=200)),
                ('hex_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PigmentType',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('description_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=6)),
                ('price', models.IntegerField(default=0)),
                ('grain', models.CharField(choices=[('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('13', 'Thirteen'), ('白', 'Byaku')], default='12', max_length=2)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.Color')),
                ('pigment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.PigmentType')),
            ],
        ),
    ]
