# Generated by Django 3.0.8 on 2020-07-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigment',
            name='grain',
        ),
    ]
