# Generated by Django 3.0.8 on 2020-07-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_auto_20200725_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='pigment',
            name='hex_code',
        ),
    ]
