# Generated by Django 4.0.6 on 2022-07-11 11:52

import colorfield.fields
from django.db import migrations, models

from colors.models import ColorFamily


def make_color_families(apps, schema_editor):
    color_families = [
        {
            'name_en': 'Red',
            'name_ja': '赤色',
            'hex_color': '#FF3500',
        },
        {
            'name_en': 'Orange',
            'name_ja': 'オレンジ色',
            'hex_color': '#FF8000',
        },
        {
            'name_en': 'Yellow',
            'name_ja': '黄色',
            'hex_color': '#FFB31A',
        },
        {
            'name_en': 'Green',
            'name_ja': '緑色',
            'hex_color': '#3D9960',
        },
        {
            'name_en': 'Blue',
            'name_ja': '青色',
            'hex_color': '#1A73FF',
        },
        {
            'name_en': 'Purple',
            'name_ja': '紫色',
            'hex_color': '#7A4DFF',
        },
        {
            'name_en': 'Pink',
            'name_ja': 'ピンク色',
            'hex_color': '#FFEEED',
        },
        {
            'name_en': 'Brown',
            'name_ja': '茶色',
            'hex_color': '#804526',
        },
        {
            'name_en': 'Grey',
            'name_ja': '鼠色',
            'hex_color': '#737373',
        },
        {
            'name_en': 'White',
            'name_ja': '白',
            'hex_color': '#FFFFFF',
        },
        {
            'name_en': 'Black',
            'name_ja': '黒',
            'hex_color': '#000000',
        }
    ]
    
    i = 0
    for color_family in color_families:
        cf = ColorFamily(name_en=color_family['name_en'], name_ja=color_family['name_ja'], hex_color=color_family['hex_color'], order=i)
        cf.save()
        i+=1

class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_auto_20200725_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('hex_color', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('order', models.IntegerField())
            ],
        ),
        migrations.RunPython(make_color_families),
    ]
