# Generated by Django 4.0.6 on 2022-07-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_colorfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_family',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.colorfamily'),
        ),
    ]
