# Generated by Django 4.0.6 on 2022-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_colorfamily_alter_color_id_alter_pigment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pigment',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
