# Generated by Django 4.0.6 on 2022-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0005_color_dark_mode_pigment_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorfamily',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
